---
- name: haproxy
  hosts: proxy
  roles:
    - geerlingguy.haproxy
  vars:
    haproxy_backend_servers:
     - name: node3
       address: 192.168.100.51:80
     - name: node4
       address: 192.168.100.52:80
  