---
# tasks file for apache2-role
- name: Install apache2
  apt:
    name: apache2
    state: latest

# start and enable apache2
- name: Start and enable apache2
  service:
    name: apache2
    state: started
    enabled: yes

# create index.html file
- name: Create index.html file
  template:
    src: index.j2
    dest: /var/www/html/index.html